apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - postgres.yaml
  - uploads-pvc.yaml
  - ingress.yaml
  - opensearch.yaml
  - indexer-cronjob.yaml
  - token-cleanup-cronjob.yaml

images:
  - name: ghcr.io/smoltech/cityforge-frontend
    newTag: latest
  - name: ghcr.io/smoltech/cityforge-indexer
    newTag: latest

namespace: cityforge
