apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres-config.yaml
  - deployment.yaml
  - service.yaml
  - postgres.yaml
  - uploads-pvc.yaml
  - ingress.yaml
  - token-cleanup-cronjob.yaml

images:
  - name: ghcr.io/smoltech/cityforge-frontend
    newTag: latest

namespace: community
